# Generated by Django 5.2.17 on 2026-10-02 05:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("method_version", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("eligible", "eligible"),
                            ("published", "published"),
                            ("superseded", "superseded"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("metric_id", models.CharField(blank=True, default="", max_length=80)),
                ("comparison", models.JSONField(default=dict)),
                ("lineage", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField()),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("observation_refs", models.JSONField(default=list)),
                ("window_start", models.DateField(null=True)),
                ("window_end", models.DateField(null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField()),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="findings.finding",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("finding", "version"), name="unique_bundle_version"
                    )
                ],
            },
        ),
    ]
