# Generated by Django 5.2.17 on 2026-10-02 03:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("relative_path", models.CharField(max_length=300)),
                ("reason", models.CharField(max_length=60)),
                ("status", models.CharField(max_length=20)),
                ("detail", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("action", models.CharField(max_length=60)),
                ("response", models.JSONField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=60)),
                ("fingerprint", models.CharField(max_length=128, unique=True)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                ("handled_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                (
                    "worker_id",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("seen_at", models.DateTimeField()),
                ("pid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_kind", models.CharField(max_length=40)),
                ("entity_id", models.CharField(max_length=64)),
                ("revision", models.IntegerField(null=True)),
                ("action", models.CharField(max_length=60)),
                ("actor", models.CharField(default="local-owner", max_length=30)),
                ("recorded_at", models.DateTimeField()),
                ("details", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_kind", "entity_id", "recorded_at"],
                        name="core_audite_entity__b8e298_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task", models.CharField(max_length=60)),
                ("scope_key", models.CharField(max_length=120)),
                ("input_key", models.CharField(max_length=120)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("leased", "leased"),
                            ("done", "done"),
                            ("failed", "failed"),
                            ("dead", "dead"),
                            ("cancelled", "cancelled"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("due_at", models.DateTimeField()),
                ("lease_owner", models.CharField(blank=True, max_length=80, null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                (
                    "safe_error",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("cursor", models.JSONField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "due_at"], name="core_job_state_456d01_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "scope_key", "input_key"),
                        name="job_unique_slot",
                    )
                ],
            },
        ),
    ]
