# Generated by Django 5.2.17 on 2026-10-02 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InspirationReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "global"),
                            ("campaign", "campaign"),
                            ("object", "object"),
                        ],
                        default="global",
                        max_length=12,
                    ),
                ),
                ("scope_ref", models.CharField(blank=True, default="", max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, default="", max_length=500)),
                ("published_at", models.DateField(null=True)),
                ("retrieved_at", models.DateTimeField()),
                ("excerpt", models.TextField(blank=True, default="")),
                ("influence", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="PeerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("handle", models.CharField(max_length=80)),
                ("label", models.CharField(max_length=200)),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("reviewed", "reviewed"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("capability", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                ("reviewed_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewedContextItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_label", models.CharField(max_length=200)),
                ("raw_text", models.TextField()),
                (
                    "meaning_state",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("confirmed", "confirmed"),
                            ("corrected", "corrected"),
                            ("rejected", "rejected"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
    ]
