# Generated by Django 5.2.17 on 2026-10-02 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="peerprofile",
            name="collection_health",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="peerprofile",
            name="instagram_username",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="peerprofile",
            name="lastfm_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="peerprofile",
            name="musicbrainz_artist_id",
            field=models.CharField(blank=True, default="", max_length=36),
        ),
        migrations.AlterField(
            model_name="peerprofile",
            name="handle",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.CreateModel(
            name="PeerCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("lastfm", "lastfm"),
                            ("manual", "manual"),
                            ("reference_artist", "reference_artist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("lastfm_url", models.URLField(blank=True, default="")),
                (
                    "lastfm_mbid",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                ("match_score", models.FloatField(null=True)),
                (
                    "musicbrainz_mbid",
                    models.CharField(blank=True, default="", max_length=36),
                ),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("provenance", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                ("reviewed_at", models.DateTimeField(null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "name"),
                        name="unique_candidate_name_per_source",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="peerprofile",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="context.peercandidate",
            ),
        ),
        migrations.CreateModel(
            name="PeerCollectionEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("collecting", "collecting"),
                            ("ok", "ok"),
                            ("failed", "failed"),
                            ("unavailable", "unavailable"),
                            ("blocked", "blocked"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("cursor", models.JSONField(default=dict)),
                ("last_snapshot", models.JSONField(default=dict)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                (
                    "peer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_entries",
                        to="context.peerprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("peer",), name="one_collection_entry_per_peer"
                    )
                ],
            },
        ),
    ]
