# Generated by Django 5.2.17 on 2026-10-02 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0002_peer_discovery_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspirationreference",
            name="collection_source",
            field=models.CharField(blank=True, default="manual", max_length=40),
        ),
        migrations.AddField(
            model_name="inspirationreference",
            name="in_analytical_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="peerprofile",
            name="peer_role",
            field=models.CharField(
                choices=[
                    ("comparable", "comparable"),
                    ("aspirational", "aspirational"),
                    ("reference_only", "reference_only"),
                    ("excluded", "excluded"),
                ],
                default="comparable",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PeerMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_id", models.CharField(max_length=80)),
                ("permalink", models.URLField(blank=True, default="", max_length=500)),
                ("caption", models.TextField(blank=True, default="")),
                ("media_type", models.CharField(blank=True, default="", max_length=40)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot", models.JSONField(default=dict)),
                ("collected_at", models.DateTimeField()),
                (
                    "peer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="context.peerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("peer", "external_id"), name="unique_peer_media"
                    )
                ],
            },
        ),
    ]
