# Generated by Django 5.2.17 on 2026-10-02 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0002_stage3_intelligence"),
    ]

    operations = [
        migrations.CreateModel(
            name="AskExchange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("scope", models.JSONField(default=dict)),
                ("answer", models.JSONField(default=dict)),
                ("generation", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("hypothesis", models.TextField()),
                ("success_measure", models.TextField()),
                ("window_start", models.DateField()),
                ("window_end", models.DateField()),
                ("protocol", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("running", "Running"),
                            ("review", "Review"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experiments",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validated", "Validated"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("kind", models.CharField(max_length=40)),
                ("payload", models.JSONField(default=dict)),
                ("evidence_bundle", models.JSONField(default=dict)),
                ("generation", models.JSONField(default=dict)),
                ("validation", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdaptationProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("summary", models.CharField(max_length=300)),
                ("diff", models.JSONField(default=dict)),
                ("evidence", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("base_campaign_revision", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptations",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "fingerprint"),
                        name="unique_adaptation_fingerprint",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SchedulingDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("requested_window", models.JSONField(default=dict)),
                ("feasible_candidates", models.JSONField(default=list)),
                ("chosen_local", models.CharField(max_length=32)),
                ("timezone", models.CharField(max_length=64)),
                ("basis", models.CharField(max_length=80)),
                ("fallback", models.BooleanField(default=False)),
                (
                    "rule_version",
                    models.CharField(default="scheduler-v1", max_length=40),
                ),
                ("evidence_refs", models.JSONField(default=list)),
                ("created_at", models.DateTimeField()),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduling_decisions",
                        to="campaigns.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("activity", "version"), name="unique_schedule_version"
                    )
                ],
            },
        ),
    ]
