# Generated by Django 5.2.17 on 2026-10-02 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_stage3_intelligence"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisSpec",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=80, unique=True)),
                ("family", models.CharField(max_length=40)),
                ("version", models.CharField(max_length=40)),
                (
                    "target_metric_id",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("config", models.JSONField(default=dict)),
                ("runnable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="CohortVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy_version", models.CharField(max_length=40)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("membership", models.JSONField(default=dict)),
                ("stale", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="FitRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cache_key", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "ready"),
                            ("exploratory", "exploratory"),
                            ("qualified", "qualified"),
                            ("insufficient_data", "insufficient_data"),
                            ("blocked", "blocked"),
                            ("stale", "stale"),
                            ("descriptive_only", "descriptive_only"),
                            ("pending", "pending"),
                            ("failed", "failed"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "blocker_code",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("lineage", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="intelligence.analysisspec",
                    ),
                ),
            ],
        ),
    ]
