# Generated by Django 5.2.17 on 2026-10-02 03:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("artist", "Artist"),
                            ("object", "Promoted object"),
                            ("account", "Account"),
                            ("content", "Content"),
                        ],
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="artist",
                        serialize=False,
                        to="catalogue.entity",
                    ),
                ),
                ("is_own", models.BooleanField(default=False)),
                ("aliases", models.JSONField(default=list)),
                ("revision", models.PositiveIntegerField(default=1)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_own", True)),
                        fields=("is_own",),
                        name="one_own_artist",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PromotedObject",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="promoted_object",
                        serialize=False,
                        to="catalogue.entity",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("recording", "Recording"),
                            ("release", "Release"),
                            ("event", "Event"),
                            ("video", "Music video"),
                            ("merch", "Merch item"),
                        ],
                        max_length=12,
                    ),
                ),
                ("key_date", models.DateField(blank=True, null=True)),
                ("key_time_local", models.TimeField(blank=True, null=True)),
                (
                    "date_precision",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("month", "Month"),
                            ("year", "Year"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "date_authority",
                    models.CharField(
                        choices=[
                            ("owner_confirmed", "Confirmed by you"),
                            ("unverified", "Unverified"),
                            ("provider", "Provider"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                ("timezone", models.CharField(blank=True, default="", max_length=64)),
                (
                    "identity_state",
                    models.CharField(
                        choices=[
                            ("pending", "Identity pending"),
                            ("confirmed", "Identity confirmed"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promoted_objects",
                        to="catalogue.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjectRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation", models.CharField(default="contains_track", max_length=20)),
                ("verified_at", models.DateTimeField(null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="catalogue.promotedobject",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalogue.promotedobject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("id_type", models.CharField(max_length=20)),
                ("external_id", models.CharField(max_length=120)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("owner_supplied", "Supplied by you"),
                            ("provider_verified", "Provider verified"),
                            ("revoked", "Revoked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("evidence", models.JSONField(default=dict)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_ids",
                        to="catalogue.entity",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("valid_to__isnull", True)),
                        fields=("provider", "id_type", "external_id"),
                        name="unique_active_external_identity",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="promotedobject",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "event"), _negated=True),
                    models.Q(("timezone", ""), _negated=True),
                    _connector="OR",
                ),
                name="event_has_timezone",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectrelation",
            constraint=models.UniqueConstraint(
                fields=("parent", "child", "relation"), name="unique_object_relation"
            ),
        ),
        migrations.AddConstraint(
            model_name="objectrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("child")), _negated=True),
                name="relation_not_self",
            ),
        ),
    ]
