# Generated by Django 5.2.17 on 2026-10-02 03:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("timezone", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("resources", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField()),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.artist",
                    ),
                ),
                (
                    "promoted_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="catalogue.promotedobject",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("purpose", models.TextField(blank=True, default="")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("content", "Content"),
                            ("operational", "Operational task"),
                            ("milestone", "Milestone"),
                        ],
                        default="content",
                        max_length=12,
                    ),
                ),
                ("channel", models.CharField(blank=True, default="", max_length=40)),
                ("format", models.CharField(blank=True, default="", max_length=40)),
                ("brief", models.TextField(blank=True, default="")),
                ("cta", models.CharField(blank=True, default="", max_length=300)),
                ("checklist", models.JSONField(default=list)),
                ("planned_at_utc", models.DateTimeField(blank=True, null=True)),
                (
                    "planned_local",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("timezone", models.CharField(max_length=64)),
                ("all_day_date", models.DateField(blank=True, null=True)),
                ("actual_at_utc", models.DateTimeField(blank=True, null=True)),
                ("actual_url", models.URLField(blank=True, default="", max_length=500)),
                ("execution_notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=10,
                    ),
                ),
                ("effort_minutes", models.PositiveIntegerField(default=0)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("manual", "Added by you"),
                            ("operational_template", "From your campaign dates"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("origin_detail", models.JSONField(default=dict)),
                (
                    "review_flag",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExecutionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prior_state", models.CharField(max_length=10)),
                ("new_state", models.CharField(max_length=10)),
                ("actual_at", models.DateTimeField(null=True)),
                ("url", models.URLField(blank=True, default="", max_length=500)),
                ("reason", models.TextField(blank=True, default="")),
                ("actor", models.CharField(default="local-owner", max_length=30)),
                ("recorded_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_events",
                        to="campaigns.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="OutcomeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("total", "Total over window"),
                            ("gain", "Gain from baseline"),
                            ("level", "Level reached"),
                        ],
                        max_length=8,
                    ),
                ),
                ("target", models.BigIntegerField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField(help_text="Exclusive")),
                ("timezone", models.CharField(max_length=64)),
                (
                    "date_basis",
                    models.CharField(help_text="utc_day or local_day", max_length=12),
                ),
                ("baseline_rule", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sources.metricdefinition",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="campaigns.outcome",
                    ),
                ),
                (
                    "scope_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("supporting", "Supporting")],
                        max_length=10,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome_links",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "outcome_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_links",
                        to="campaigns.outcomeversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome_links",
                        to="campaigns.activity",
                    ),
                ),
                (
                    "outcome_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaigns.outcomeversion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="campaign_window_order",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["campaign", "planned_at_utc", "status"],
                name="campaigns_a_campaig_d362e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["all_day_date"], name="campaigns_a_all_day_e1e490_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("planned_at_utc__isnull", True),
                    ("all_day_date__isnull", True),
                    _connector="OR",
                ),
                name="timed_xor_all_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "completed"), _negated=True),
                    ("actual_at_utc__isnull", False),
                    _connector="OR",
                ),
                name="completed_has_actual",
            ),
        ),
        migrations.AddConstraint(
            model_name="outcomeversion",
            constraint=models.UniqueConstraint(
                fields=("outcome", "version"), name="unique_outcome_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="outcomeversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gt", models.F("period_start"))),
                name="outcome_window_half_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="outcomeversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("target__gte", 0)),
                name="outcome_target_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignoutcome",
            constraint=models.UniqueConstraint(
                fields=("campaign", "outcome_version"), name="unique_campaign_outcome"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignoutcome",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "primary")),
                fields=("campaign",),
                name="one_primary_outcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityoutcome",
            constraint=models.UniqueConstraint(
                fields=("activity", "outcome_version"), name="unique_activity_outcome"
            ),
        ),
    ]
