# Generated by Django 5.2.17 on 2026-10-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="origin",
            field=models.CharField(
                choices=[
                    ("manual", "Added by you"),
                    ("operational_template", "From your campaign dates"),
                    ("evidence_recommendation", "Evidence-backed suggestion"),
                ],
                default="manual",
                max_length=24,
            ),
        ),
    ]
