# Generated by Django 5.2.17 on 2026-10-02 03:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("relative_path", models.CharField(max_length=200, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("size_bytes", models.PositiveIntegerField()),
                ("received_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("scope", models.CharField(blank=True, default="", max_length=12)),
                ("parser_version", models.CharField(max_length=40)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("staged", "staged"),
                            ("invalid", "invalid"),
                            ("committed", "committed"),
                            ("rejected", "rejected"),
                            ("undone", "undone"),
                        ],
                        default="staged",
                        max_length=12,
                    ),
                ),
                ("preview_revision", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField()),
                ("committed_at", models.DateTimeField(null=True)),
                ("undone_at", models.DateTimeField(null=True)),
                ("undo_reason", models.TextField(blank=True, default="")),
                ("summary", models.JSONField(default=dict)),
                (
                    "mapped_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.entity",
                    ),
                ),
                (
                    "raw_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="sources.rawfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetricDefinition",
            fields=[
                (
                    "id",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("provider", models.CharField(max_length=40)),
                ("code", models.CharField(max_length=60)),
                ("version", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=120)),
                ("unit", models.CharField(default="count", max_length=20)),
                ("grain", models.CharField(max_length=20)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("flow", "Daily flow"),
                            ("stock", "Stock snapshot"),
                            ("rolling_stock", "Rolling 28-day snapshot"),
                            ("nested_stock", "Nested rolling subset"),
                            ("daily_unique", "Daily unique count"),
                            ("cumulative", "Cumulative snapshot"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope_kind", models.CharField(max_length=12)),
                ("definition", models.TextField()),
                ("outcome_modes", models.JSONField(default=list)),
                ("csv_column", models.CharField(blank=True, default="", max_length=60)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sources.metricdefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "dimension_key",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="catalogue.entity",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sources.metricdefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservationVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("value", models.BigIntegerField(null=True)),
                (
                    "missing_reason",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("observed_at", models.DateTimeField(null=True)),
                ("available_at", models.DateTimeField()),
                ("source_row_ref", models.CharField(max_length=200)),
                ("revision_reason", models.TextField(blank=True, default="")),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="sources.observation",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sources.observationversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservationContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("row_ref", models.CharField(max_length=200)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributions",
                        to="sources.importbatch",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributions",
                        to="sources.observationversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="observation",
            name="active_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="sources.observationversion",
            ),
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("route", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, default="")),
                (
                    "secret_ref",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("fixture_class", models.CharField(default="owner", max_length=10)),
                ("state", models.CharField(default="active", max_length=20)),
                ("capability", models.JSONField(default=dict)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "account_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.entity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="observation",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="sources.source"
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="sources.source",
            ),
        ),
        migrations.CreateModel(
            name="SourcePolicyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("purposes", models.JSONField()),
                ("conditions", models.TextField(blank=True, default="")),
                ("assessment_ref", models.TextField()),
                ("effective_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(null=True)),
                ("retention", models.JSONField(default=dict)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="observationversion",
            name="policy_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sources.sourcepolicyversion",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="policy_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="sources.sourcepolicyversion",
            ),
        ),
        migrations.CreateModel(
            name="StagedIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField(null=True)),
                ("column", models.CharField(blank=True, default="", max_length=60)),
                ("code", models.CharField(max_length=40)),
                ("message", models.CharField(max_length=300)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="sources.importbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StagedObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("period_start", models.DateField()),
                ("value", models.BigIntegerField()),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("equal", "equal"),
                            ("conflict", "conflict"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("approval_reason", models.TextField(blank=True, default="")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staged",
                        to="sources.importbatch",
                    ),
                ),
                (
                    "existing_version",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sources.observationversion",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sources.metricdefinition",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="metricdefinition",
            constraint=models.UniqueConstraint(
                fields=("provider", "code", "version"), name="unique_metric_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="observationcontribution",
            constraint=models.UniqueConstraint(
                fields=("version", "batch"), name="unique_contribution"
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("provider", "route"), name="unique_provider_route"
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["entity", "metric", "period_start"],
                name="sources_obs_entity__72dff9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.UniqueConstraint(
                fields=(
                    "source",
                    "entity",
                    "metric",
                    "period_start",
                    "period_end",
                    "dimension_key",
                ),
                name="unique_observation_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gt", models.F("period_start"))),
                name="observation_half_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcepolicyversion",
            constraint=models.UniqueConstraint(
                fields=("source", "version"), name="unique_policy_version"
            ),
        ),
        migrations.AddIndex(
            model_name="observationversion",
            index=models.Index(
                fields=["available_at"], name="sources_obs_availab_847fd9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="observationversion",
            constraint=models.UniqueConstraint(
                fields=("observation", "version"), name="unique_observation_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="observationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("value__isnull", False), ("missing_reason", "")),
                    models.Q(
                        ("value__isnull", True),
                        models.Q(("missing_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="value_xor_missing",
            ),
        ),
        migrations.AddConstraint(
            model_name="observationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("value__isnull", True), ("value__gte", 0), _connector="OR"
                ),
                name="count_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagedobservation",
            constraint=models.UniqueConstraint(
                fields=("batch", "metric", "period_start"), name="unique_staged_key"
            ),
        ),
    ]
